on:
  pull_request:
    branches:    
      - main
    paths:
      - 'backend/**'

jobs:
  backend:
    name: 'Backend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
       
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - run: cd backend

      - run: npm install

      - run: npm run lint

      - run: npm test

      - run: npm run build

      - run: npm test
