on:
  push:
    paths:
      - 'backend/**'
  
env:
  tf_actions_working_dir: 'backend'

jobs:
  backend:
    name: 'Backend'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - run: npm install

      - run: npm run lint

      - run: npm test

      - run: npm run build

      - run: npm test
