on:
  pull_request:
    branches:    
      - main
    paths:
      - 'frontend/**'

jobs:
  frontend:
    name: 'Frontend'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
       
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - run: cd frontend && npm install

      # - run: cd frontend && npm run build
